/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Abnormal: typeof import('./src/components/Mobile/Home/Abnormal.vue')['default']
    AddCar: typeof import('./src/components/Mobile/Filings/AddCar.vue')['default']
    ChangePsw: typeof import('./src/components/Mobile/User/ChangePsw.vue')['default']
    Confirmation: typeof import('./src/components/Mobile/Home/Confirmation.vue')['default']
    DetailInfo: typeof import('./src/components/Mobile/User/DetailInfo.vue')['default']
    Filings: typeof import('./src/components/Mobile/Filings/index.vue')['default']
    Home: typeof import('./src/components/Mobile/Home/index.vue')['default']
    Loading: typeof import('./src/components/Mobile/Home/Loading.vue')['default']
    Login: typeof import('./src/components/Mobile/Login.vue')['default']
    Outbound: typeof import('./src/components/Mobile/Home/Outbound.vue')['default']
    PC: typeof import('./src/components/PC/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableChart: typeof import('./src/components/TableChart/index.vue')['default']
    Tallying: typeof import('./src/components/Mobile/Home/Tallying.vue')['default']
    TallyingTable: typeof import('./src/components/PC/TallyingTable.vue')['default']
    UpdateCar: typeof import('./src/components/Mobile/Filings/UpdateCar.vue')['default']
    User: typeof import('./src/components/Mobile/User/index.vue')['default']
    UserTable: typeof import('./src/components/PC/UserTable.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    Warehousing: typeof import('./src/components/Mobile/Home/Warehousing.vue')['default']
  }
}
